[versions]
kotlin-plugins-version = "2.0.0"
quarkus = "3.12.1"
quarkus-jandex = "2.0.0"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin-plugins-version" }
kotlin-allopen-plugin = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin-plugins-version"  }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version = "7.0.0" }
quarkus-plugin = { module = "io.quarkus:gradle-application-plugin", version.ref = "quarkus" }
quarkus-platform = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
quarkus-arc = { module = "io.quarkus:quarkus-arc" }
quarkus-kotlin-extension = { module = "io.quarkus:quarkus-kotlin" }
quarkus-kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8" }
quarkus-jandex = { module = "org.kordamp.gradle:jandex-gradle-plugin", version.ref = "quarkus-jandex" }
